name: Go CI

on:
  workflow_dispatch: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test ./... -v
      - name: Build binary
        run: go build -o workmateTestProject main.go
